/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 4e17075263e86f857e96b211056d84b1)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/worker");
	}
	interface Env {
		TEENY_PRIMARY_DB: D1Database;
		LOADER: WorkerLoader;
		ASSETS: Fetcher;
		MIGRATE_UI_USER: "admin";
		MIGRATE_UI_PASSWORD: string;
		DEBUG_ERRORS: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MIGRATE_UI_USER" | "MIGRATE_UI_PASSWORD" | "DEBUG_ERRORS">> {}
}
